### ISSUE TITLE
Errors with the RapyServiceProvider.php

### ISSUE THREAD

**Issue by EhtuCom** [zofe/rapyd-livewire#4]
Hi!

Question n1:
If I don't copy the /vendor/zofe/.../config/rapyd-livewire.php to the main config folder it doesn't get the rapyLivewire configuration, is that right? Because I don't know if that happens because my app it's upgraded from Lara7 to Lara10 and may be I lost something on the upgrades.

Question n2:
After copying this file I continue having some problems and I've to edit RapydServiceProvider to work:
1: This "...include_styles.**bootstrap**" to just "...include_styles" because if not I get an error because the 2nd parameter is no an array of the styles
2: and this "rapyd_livewire" to "rapyd-livewire" may be this is because of the way that I copied the config file to the app config folder
as in the image below:

![image](https://user-images.githubusercontent.com/4345616/222258835-463efe73-585d-4abe-87d2-1a01e523a729.png)

If I don't make this changes I get the following error:
![image](https://user-images.githubusercontent.com/4345616/222261111-52db7b68-1486-4790-b4ae-1d6c8d7f4e52.png)

Thank you in advance,
David Lyons

**Comment by zofe** [comment]
thnks, I've fixes wrong config file name reference from rapyd_livewire to rapyd-livewire in current stable 0.8.37
I hope it solves the problem.

**Comment by EhtuCom** [comment]
Hi!

It still shows me an exception:
![image](https://user-images.githubusercontent.com/4345616/224114728-a134a1dd-a659-47f0-afc8-93bfaebfba04.png)

I stil have to edit the RapydServiceProvider and change this line:
if (in_array('bootstrap', config('rapyd-livewire.include_styles.bootstrap'))) { ...
to
if (in_array('bootstrap', config('rapyd-livewire.include_styles'))) {
![image](https://user-images.githubusercontent.com/4345616/224114144-6e430586-50fc-425f-adcf-74d8e193ae71.png)

**Comment by zofe** [comment]
sorry, may be solved in current 0.8.39
